# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - mysql -e 'create database cropanbot;'
  - export DB_DATABASE='cropanbot'
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - php artisan migrate --seed --force
  - php artisan key:generate

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always