<?php

namespace Cropan;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\QueryException;
use Symfony\Component\Debug\Exception\FatalThrowableError;
use \Telegram\Bot\Objects\Update as UpdateObject;

class Update extends Model
{
    use SoftDeletes;
    protected $table = 'updates';
    protected $fillable = ['update_id', 'user_id', 'type', 'reply_to', 'text', 'content', 'date'];

    // Events
    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (Update $update) {
            Picture::create([
                'url' => $update->text,
                'user_id' => $update->user_id
            ]);

            $update->delete();
        });
    }
}
